### ISSUE TITLE
[ADD] [Multiple Lines Support] - Support Folded Lines and QuotedPrintable, per RFC

### ISSUE THREAD

**Issue by henrihein** [Aptivi/VisualCard#2]
### Description of new feature
The specification for vCards has support for multiple lines in the vCard file that represent a single logical line. There are two features that can result in multiple lines: 

1.  Line folding. See section 3.2: https://www.rfc-editor.org/rfc/rfc6350#section-3.2
2. The Quoted-Printable encoding. See https://www.ietf.org/rfc/rfc2045.txt, section 6.7. This was only supported for vCards prior to version 3.0, but since VisualCard do support v2.0 cards, I think it would be nice to also support Quoted-Printable. 

The presence of either of these currently breaks VisualCard. When I load a file with either folded lines or a v2.0 vCard with a Quoted-Printable encoded field, the file fails to load.

### What does it add?
- [ Line Unfolding] Support folded lines by unfolding them.
- [ Quoted-Printable encoding] Support combining multiple lines in a field with the Quoted-Printable encoding. I don't propose decoding the encoding, just pick up all the lines for the field and then continue, so that it does not break loading files containing the encoding. 

### Have you tried doing it? If so, attach a mod file.
Yes, but the vCard files contain private contacts I don't wish to share. If needed, I can create test cases that demonstrate the issues.

**Comment by henrihein** [comment]
I have a local branch that implements support for the above. If you want, I can submit it as a PR.

**Comment by AptiviCEO** [comment]
Thank you for your contribution and usage of VC to make it better.

Yes, you can submit it as a PR. We need test cases, though. Just create vcf files that demonstrate those cases without giving private info, and we'll review the PR. Currently, VisualCard supports only folded lines that are preceded with either a space or a tab at the beginning of the line, but it would be nice to add those as you suggested.

**Comment by henrihein** [comment]
Great! I'll be happy to put together some test cases with dummy data. I think I will need permission to push a PR branch.

**Comment by AptiviCEO** [comment]
You don't need to push directly to the PR branch in this repo. Instead, you can fork the project, put your changes, and make a PR out of it. You won't need permissions this way.

**Comment by henrihein** [comment]
Thanks for the tip. I haven't before submitted PRs across forks, so didn't think to do it that way. I am busy this week with my day-job but should have something for you this weekend.

**Comment by AptiviCEO** [comment]
You are welcome. I'll be on the lookout for the PR, so take your time. Again, thanks for your contribution to VisualCard.

**Comment by henrihein** [comment]
[testcases.zip](https://github.com/user-attachments/files/18236318/testcases.zip)
PR submitted. These are my test cases. They aren't particularly sophisticated. Just a few mostly identical contacts in various combinations. The data is all dummy data (although the Base64 decodes to valid randomly generated PNGs). I tried loading these into the ShowContacts demo program. The ones with multi-line QuotedPrintable fails before the PR and succeeds with the changes.
